# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.directoryBox = QtWidgets.QLineEdit(self.centralwidget)
        self.directoryBox.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.directoryBox.setObjectName("directoryBox")
        self.dirButton = QtWidgets.QPushButton(self.centralwidget)
        self.dirButton.setGeometry(QtCore.QRect(450, 20, 21, 21))
        self.dirButton.setObjectName("dirButton")
        self.poniBox = QtWidgets.QLineEdit(self.centralwidget)
        self.poniBox.setGeometry(QtCore.QRect(10, 60, 431, 20))
        self.poniBox.setObjectName("poniBox")
        self.maskBox = QtWidgets.QLineEdit(self.centralwidget)
        self.maskBox.setGeometry(QtCore.QRect(10, 100, 431, 20))
        self.maskBox.setObjectName("maskBox")
        self.gainMapBox = QtWidgets.QLineEdit(self.centralwidget)
        self.gainMapBox.setGeometry(QtCore.QRect(10, 140, 431, 20))
        self.gainMapBox.setObjectName("gainMapBox")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(420, 230, 75, 23))
        self.runButton.setObjectName("runButton")
        self.maskButton = QtWidgets.QPushButton(self.centralwidget)
        self.maskButton.setGeometry(QtCore.QRect(450, 100, 21, 21))
        self.maskButton.setObjectName("maskButton")
        self.poniButton = QtWidgets.QPushButton(self.centralwidget)
        self.poniButton.setGeometry(QtCore.QRect(450, 60, 21, 21))
        self.poniButton.setObjectName("poniButton")
        self.gainMapButton = QtWidgets.QPushButton(self.centralwidget)
        self.gainMapButton.setGeometry(QtCore.QRect(450, 140, 21, 21))
        self.gainMapButton.setObjectName("gainMapButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 140, 71, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dirButton.setText(_translate("MainWindow", "..."))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.maskButton.setText(_translate("MainWindow", "..."))
        self.poniButton.setText(_translate("MainWindow", "..."))
        self.gainMapButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "directory"))
        self.label_2.setText(_translate("MainWindow", "poni file"))
        self.label_3.setText(_translate("MainWindow", "mask file"))
        self.label_4.setText(_translate("MainWindow", "gain map file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
